-- MySQL Script generated by MySQL Workbench
-- mar 04 feb 2020 11:07:10 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concesionariodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionariodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionariodb` DEFAULT CHARACTER SET utf8 ;
USE `concesionariodb` ;

-- -----------------------------------------------------
-- Table `concesionariodb`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionariodb`.`Vendedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concesionariodb`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionariodb`.`Coche` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `estado` ENUM('Nuevo', 'Segunda_Mano', 'Km_0') NULL DEFAULT 'Nuevo',
  `vendedor_id` INT NOT NULL,
  `anyo` DATE NOT NULL,
  `potencia` INT NULL,
  `motor` ENUM('Gasolina', 'Diesel', 'Hibrido', 'Electrico') NOT NULL DEFAULT 'Gasolina',
  `disponible` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `vendedor_id`),
  INDEX `fk_Coches_Vendedor_idx` (`vendedor_id` ASC),
  CONSTRAINT `fk_Coches_Vendedor`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `concesionariodb`.`Vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `concesionariodb`.`Vendedor`
-- -----------------------------------------------------
START TRANSACTION;
USE `concesionariodb`;
INSERT INTO `concesionariodb`.`Vendedor` (`id`, `usuario`, `pass`, `nombre`, `apellido`) VALUES (1, 'nicolas', '123456', 'Nicolas', 'Pons');
INSERT INTO `concesionariodb`.`Vendedor` (`id`, `usuario`, `pass`, `nombre`, `apellido`) VALUES (2, 'carles', '654321', 'Carles', 'Chovi');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concesionariodb`.`Coche`
-- -----------------------------------------------------
START TRANSACTION;
USE `concesionariodb`;
INSERT INTO `concesionariodb`.`Coche` (`id`, `marca`, `modelo`, `matricula`, `precio`, `estado`, `vendedor_id`, `anyo`, `potencia`, `motor`, `disponible`) VALUES (1, 'Ford', 'Fiesta', '1234ABC', 15000, 'Nuevo', , '2016', 120, 'Gasolina', 1);
INSERT INTO `concesionariodb`.`Coche` (`id`, `marca`, `modelo`, `matricula`, `precio`, `estado`, `vendedor_id`, `anyo`, `potencia`, `motor`, `disponible`) VALUES (2, 'Ford', 'Focus', '456789DFG', 32000, 'Nuevo', , '2016', 180, 'Gasolina', 1);
INSERT INTO `concesionariodb`.`Coche` (`id`, `marca`, `modelo`, `matricula`, `precio`, `estado`, `vendedor_id`, `anyo`, `potencia`, `motor`, `disponible`) VALUES (3, 'Toyota', 'RAV4', '258963HTU', 45000, 'Nuevo', , '2019', 150, 'Hibrido', 1);
INSERT INTO `concesionariodb`.`Coche` (`id`, `marca`, `modelo`, `matricula`, `precio`, `estado`, `vendedor_id`, `anyo`, `potencia`, `motor`, `disponible`) VALUES (4, 'Seat', 'Ibiza', '741258GTH', 3000, 'Segunda_Mano', , '2003', 90, 'Diesel', 1);
INSERT INTO `concesionariodb`.`Coche` (`id`, `marca`, `modelo`, `matricula`, `precio`, `estado`, `vendedor_id`, `anyo`, `potencia`, `motor`, `disponible`) VALUES (5, 'Volkswagen', 'Polo', '789123BVJ', 7500, 'KM_0', , '2018', 95, 'Gasolina', 1);

COMMIT;

